import type { AppData, OrbitEvent, Person, SocialRep } from "@/lib/types";
import { emptyAppData } from "./adapter";
import { generateWeeklySocialPlan } from "@/lib/ai/mock/plans";

// Jersey City / NYC seed data. Recurring events weighted, faith/community
// events first-class, nothing bar-centric.

function iso(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().slice(0, 10);
}

function ev(partial: Partial<OrbitEvent> & { id: string; title: string; date: string }): OrbitEvent {
  return {
    startTime: undefined,
    endTime: undefined,
    location: undefined,
    neighborhood: undefined,
    cost: 0,
    url: undefined,
    eventType: "other",
    vibeTags: [],
    soloFriendliness: 3,
    conversationPotential: 3,
    repeatPotential: 3,
    socialDifficulty: 3,
    isRecurring: false,
    timesAttended: 0,
    notes: undefined,
    status: "interested",
    createdAt: new Date().toISOString(),
    ...partial,
  };
}

const seedEvents: OrbitEvent[] = [
  ev({
    id: "seed-run-club",
    title: "Grove Street Run Club",
    date: iso(2),
    startTime: "18:30",
    endTime: "20:00",
    location: "Grove St PATH plaza",
    neighborhood: "Downtown JC",
    eventType: "run-club",
    vibeTags: ["fitness", "outdoors", "regulars"],
    soloFriendliness: 5,
    conversationPotential: 4,
    repeatPotential: 5,
    socialDifficulty: 2,
    isRecurring: true,
    status: "planned",
    notes: "Weekly. Easy 5k pace group, coffee after.",
  }),
  ev({
    id: "seed-comic-club",
    title: "Comic Book Club Night",
    date: iso(4),
    startTime: "19:00",
    location: "WORD Bookstore",
    neighborhood: "Downtown JC",
    cost: 0,
    eventType: "comic-club",
    vibeTags: ["nerdy", "small-group"],
    soloFriendliness: 4,
    conversationPotential: 5,
    repeatPotential: 5,
    socialDifficulty: 2,
    isRecurring: true,
  }),
  ev({
    id: "seed-improv",
    title: "Intro Improv Class",
    date: iso(6),
    startTime: "19:30",
    location: "Manhattan (Chelsea)",
    neighborhood: "Manhattan",
    cost: 30,
    eventType: "improv-class",
    vibeTags: ["creative", "structured"],
    soloFriendliness: 5,
    conversationPotential: 5,
    repeatPotential: 4,
    socialDifficulty: 4,
    isRecurring: true,
  }),
  ev({
    id: "seed-mosque-night",
    title: "Mosque Community Night",
    date: iso(3),
    startTime: "19:00",
    location: "Journal Square",
    neighborhood: "Journal Square",
    eventType: "faith-community",
    vibeTags: ["community", "welcoming"],
    soloFriendliness: 5,
    conversationPotential: 4,
    repeatPotential: 5,
    socialDifficulty: 2,
    isRecurring: true,
  }),
  ev({
    id: "seed-volunteer",
    title: "Community Fridge Volunteer Shift",
    date: iso(5),
    startTime: "10:00",
    endTime: "12:00",
    location: "McGinley Square",
    neighborhood: "McGinley Square",
    eventType: "volunteer",
    vibeTags: ["service", "side-by-side"],
    soloFriendliness: 5,
    conversationPotential: 4,
    repeatPotential: 4,
    socialDifficulty: 1,
    isRecurring: true,
  }),
  ev({
    id: "seed-museum",
    title: "Museum Late Night",
    date: iso(8),
    startTime: "18:00",
    location: "Manhattan",
    neighborhood: "Manhattan",
    cost: 25,
    eventType: "museum",
    vibeTags: ["culture", "quiet"],
    soloFriendliness: 5,
    conversationPotential: 2,
    repeatPotential: 3,
    socialDifficulty: 1,
  }),
  ev({
    id: "seed-board-games",
    title: "Board Game Night",
    date: iso(7),
    startTime: "19:00",
    location: "Downtown JC cafe",
    neighborhood: "Downtown JC",
    cost: 5,
    eventType: "board-games",
    vibeTags: ["structured", "small-group"],
    soloFriendliness: 4,
    conversationPotential: 5,
    repeatPotential: 5,
    socialDifficulty: 2,
    isRecurring: true,
  }),
  ev({
    id: "seed-bookstore",
    title: "Bookstore Author Reading",
    date: iso(9),
    startTime: "19:00",
    location: "Grove St",
    neighborhood: "Downtown JC",
    eventType: "bookstore",
    vibeTags: ["quiet", "culture"],
    soloFriendliness: 5,
    conversationPotential: 3,
    repeatPotential: 3,
    socialDifficulty: 2,
  }),
  ev({
    id: "seed-fitness",
    title: "Saturday Fitness Class",
    date: iso(6),
    startTime: "09:00",
    location: "Hamilton Park",
    neighborhood: "Downtown JC",
    cost: 15,
    eventType: "fitness-class",
    vibeTags: ["fitness", "morning"],
    soloFriendliness: 5,
    conversationPotential: 3,
    repeatPotential: 5,
    socialDifficulty: 2,
    isRecurring: true,
  }),
  ev({
    id: "seed-pro-meetup",
    title: "Fintech Professionals Meetup",
    date: iso(10),
    startTime: "18:30",
    location: "Manhattan (FiDi)",
    neighborhood: "Manhattan",
    eventType: "professional",
    vibeTags: ["professional", "name-tags"],
    soloFriendliness: 3,
    conversationPotential: 4,
    repeatPotential: 4,
    socialDifficulty: 4,
    isRecurring: true,
  }),
  ev({
    id: "seed-coffee-reading",
    title: "Coffee Shop Reading Night",
    date: iso(1),
    startTime: "19:00",
    location: "Journal Square cafe",
    neighborhood: "Journal Square",
    cost: 6,
    eventType: "coffee-night",
    vibeTags: ["quiet", "solo-friendly"],
    soloFriendliness: 5,
    conversationPotential: 2,
    repeatPotential: 4,
    socialDifficulty: 1,
    isRecurring: true,
    status: "planned",
  }),
  ev({
    id: "seed-walk-group",
    title: "Neighborhood Walk Group",
    date: iso(-2),
    startTime: "08:00",
    location: "Liberty State Park",
    neighborhood: "Downtown JC",
    eventType: "walk-group",
    vibeTags: ["outdoors", "easy-conversation"],
    soloFriendliness: 5,
    conversationPotential: 4,
    repeatPotential: 5,
    socialDifficulty: 1,
    isRecurring: true,
    status: "attended",
    timesAttended: 1,
    reflection: {
      talkedToAnyone: true,
      peopleMet: ["seed-person-omar"],
      exchangedContact: true,
      wouldAttendAgain: true,
      learned: "Easier to talk while walking than standing around.",
      energyAfter: "better",
    },
  }),
];

const seedPeople: Person[] = [
  {
    id: "seed-person-omar",
    name: "Omar",
    context: "Walks the full loop, works in logistics",
    whereMet: "Neighborhood Walk Group",
    dateMet: iso(-2),
    lane: "potential-friend",
    vibe: "Easygoing, dry humor",
    sharedInterests: ["walking", "coffee", "soccer"],
    preferredChannel: "whatsapp",
    phone: "+15551230000",
    lastContacted: undefined,
    nextFollowUp: iso(0),
    cadenceDays: 7,
    status: "needs-follow-up",
    messagesSentWithoutResponse: 0,
    hasResponded: false,
    createdAt: new Date().toISOString(),
    notes: "Said he comes most Saturdays.",
  },
  {
    id: "seed-person-dana",
    name: "Dana",
    context: "Organizer of the comic book club",
    whereMet: "WORD Bookstore",
    dateMet: iso(-14),
    lane: "community-contact",
    vibe: "Welcoming, knows everyone",
    sharedInterests: ["comics", "sci-fi"],
    preferredChannel: "email",
    email: "dana@example.com",
    lastContacted: iso(-10),
    cadenceDays: 14,
    status: "active",
    messagesSentWithoutResponse: 0,
    hasResponded: true,
    createdAt: new Date().toISOString(),
  },
];

const seedReps: SocialRep[] = [
  {
    id: "seed-rep-1",
    type: "left-apartment",
    date: iso(-2),
    eventId: "seed-walk-group",
  },
  {
    id: "seed-rep-2",
    type: "attended-event",
    date: iso(-2),
    eventId: "seed-walk-group",
  },
  {
    id: "seed-rep-3",
    type: "introduced-self",
    date: iso(-2),
    eventId: "seed-walk-group",
    personId: "seed-person-omar",
  },
  {
    id: "seed-rep-4",
    type: "added-person",
    date: iso(-2),
    personId: "seed-person-omar",
  },
];

export function seedAppData(): AppData {
  const base = emptyAppData();
  const data: AppData = {
    ...base,
    mode: "demo",
    profile: {
      name: "Demo",
      city: "Jersey City",
      neighborhood: "Journal Square",
      ageRange: "35-44",
      goal: "make-friends",
      energy: "medium",
      preferredSettings: [
        "run-clubs",
        "book-comic-clubs",
        "faith-community",
        "coffee-shops",
        "fitness",
        "volunteering",
      ],
      avoidedSettings: ["bars", "heavy-nightlife", "loud-parties"],
      weeklyAvailability: ["Tue", "Thu", "Sat", "Sun"],
      budgetPerOuting: 30,
      comfortWithStrangers: "comfortable-but-rusty",
      preferredChannel: "whatsapp",
      onboardedAt: new Date().toISOString(),
    },
    events: seedEvents,
    people: seedPeople,
    reps: seedReps,
    cityPacks: [
      {
        id: "seed-citypack-jc",
        name: "Jersey City Social Rebuild",
        city: "Jersey City",
        description:
          "Recurring anchors across Journal Square, Grove St, and downtown JC.",
        eventTemplates: [],
      },
    ],
    personaPacks: [
      {
        id: "seed-persona-newcity",
        name: "New City Reset",
        persona: "new-city-transplant",
        description:
          "A four-week emphasis on recurring events and becoming a regular.",
        weeklyEmphasis: [
          "Pick two recurring anchors",
          "Return to both",
          "Capture one weak tie per week",
          "Follow up within 48 hours",
        ],
      },
    ],
  };
  if (data.profile) {
    data.plans = [generateWeeklySocialPlan(data.profile, data.events)];
  }
  return data;
}
