// 15 Instagram carousel packages, 6-9 slides each. Slide 1 = cover (big),
// last slide = CTA (bordered). *word* = accent.

const HT = "#adultfriendship #makingfriends #sociallife #socialskills";

export const carousels = [
  {
    slug: "01-seven-social-reps",
    title: "The 7 social reps adults need",
    caption: "Social fitness is real fitness. These 7 reps, tracked weekly, rebuild a social life faster than any personality change.\n\nWhich one are you skipping? (Be honest — it's #6 for most people.)\n\nTry the 7-day plan → link in bio.\n\n" + HT + " #habits",
    hashtags: ["#adultfriendship", "#socialskills", "#habits", "#selfimprovement"],
    uploadNotes: "Strong opener carousel. Post week 1. Prompt in caption drives comments.",
    slides: [
      { headline: "The 7 social reps\nadults actually need", body: "Track them like training.\nBecause that's what this is." },
      { headline: "1. Leave the apartment\n*on purpose*", body: "Not errands. A chosen outing.\nSolo-but-public counts completely." },
      { headline: "2. Stay 45 minutes", body: "Long enough for something\nto happen. Short enough\nto say yes to." },
      { headline: "3. Ask one person\none question", body: "“How did you find this event?”\nis the best opener in the building." },
      { headline: "4. Learn one name.\nUse it once.", body: "Names are the cheapest\ninvestment in familiarity." },
      { headline: "5. Capture the weak tie", body: "Write down who you met and where\n— before you forget the details\nthat make follow-up easy." },
      { headline: "6. Send the follow-up\nwithin 72 hours", body: "The rep everyone skips.\nThe one that builds friendships." },
      { headline: "7. Return to the\nsame place", body: "Repeat exposure is the mechanism.\nThe third visit changes everything." },
      { headline: "One rep today.", body: "The app tracks all seven —\nprivately, no feed.", footer: "Try the 7-day plan → link in bio" },
    ],
  },
  {
    slug: "02-why-weak-ties-die",
    title: "Why weak ties die",
    register: "mirror",
    caption: "The connection didn't fail. It just never got maintained.\n\nWeak ties — the people you know a little and like — are where friendships come from. And they have a half-life.\n\nOne low-pressure message this week. That's the fix.\n\n" + HT + " #weakties",
    hashtags: ["#adultfriendship", "#weakties", "#makingfriends"],
    uploadNotes: "Mirror register (clay accent). Pairs with video 03 in the same week.",
    slides: [
      { headline: "Why weak ties die", body: "(and why it's nobody's fault)" },
      { headline: "A weak tie is someone you\nknow a little — and like", body: "The run club person.\nThe coworker from the old job.\nThe friend-of-a-friend you clicked with." },
      { headline: "Weak ties are where\nfriendships come from", body: "Almost no one becomes your friend\nas a stranger. They pass through\nweak-tie territory first." },
      { headline: "But weak ties have\na *half-life*", body: "Every silent week, the odds decay.\nAfter a month, you're basically\nstrangers with shared trivia." },
      { headline: "Both people assume\nthe other will reach out", body: "So neither does.\nThe tie dies of symmetry." },
      { headline: "The maintenance dose\nis tiny", body: "One low-pressure message.\n“Good meeting you — I'm going\nagain next week.”" },
      { headline: "Send one this week.", body: "Orbit tracks who's drifting\nand drafts the message.", footer: "Link in bio" },
    ],
  },
  {
    slug: "03-follow-up-after-meeting-once",
    title: "How to follow up after meeting someone once",
    caption: "Exact scripts, because 'just text them' isn't advice.\n\nThe 72-hour window matters more than the wording. Save this for the next time you meet someone worth knowing.\n\n" + HT + " #followup",
    hashtags: ["#adultfriendship", "#socialskills", "#followup"],
    uploadNotes: "Script-format = highest saves. Don't shorten the examples.",
    slides: [
      { headline: "How to follow up after\nmeeting someone *once*", body: "Without being weird about it." },
      { headline: "Rule 1: within 72 hours", body: "Day 3 they remember you warmly.\nWeek 2 you need a reintroduction.\nTiming beats wording." },
      { headline: "Rule 2: reference the place,\nnot the person", body: "“Good meeting you at the run club”\nfeels casual.\n“I really enjoyed meeting YOU”\nfeels heavy. Same sentiment." },
      { headline: "Script: the recurring anchor", body: "“Hey — good meeting you Thursday.\nI'm going again next week.\nYou planning to be there?”" },
      { headline: "Script: the zero-pressure hello", body: "“Good meeting you the other day.\nNo need to reply — just didn't want\nto be the person who says 'stay\nin touch' and never does.”" },
      { headline: "Rule 3: one message,\nthen let it breathe", body: "If they don't answer, the door\nstays open. Two unanswered\nmessages = stop." },
      { headline: "The move is light + repeated", body: "Not intense + rare.\nLet the second meeting\ndo the heavy lifting." },
      { headline: "Orbit drafts these for you", body: "Six tones, honest risk levels,\nand you hit send — never the app.", footer: "Try it free → link in bio" },
    ],
  },
  {
    slug: "04-recurring-beats-random",
    title: "Why recurring events beat random meetups",
    caption: "15 events this year. None twice. That's the bug.\n\nMere exposure is the most boring, most reliable force in social psychology — and almost nobody uses it deliberately.\n\nPick one thing. Go three times.\n\n" + HT + " #community",
    hashtags: ["#adultfriendship", "#makingfriends", "#community"],
    uploadNotes: "Core thesis carousel. Evergreen — safe to repost quarterly.",
    slides: [
      { headline: "Why recurring events beat\nrandom meetups", body: "Every time. For everyone." },
      { headline: "Random events start you at\n*stranger-zero*", body: "New room, new faces,\nfull cold-start cost —\nevery single time." },
      { headline: "Recurring events\n*compound*", body: "Visit 1: stranger\nVisit 2: familiar face\nVisit 3: expected\nVisit 5: regular" },
      { headline: "“Expected” is the\nmagic threshold", body: "People who are expected\nget greeted, get noticed missing,\nget invited to things." },
      { headline: "The psychology is boring\nand bulletproof", body: "Mere exposure: we warm to people\nwe've simply seen before.\nNo charisma required." },
      { headline: "The math favors you too", body: "10 random events = 10 cold starts.\n10 visits to 2 anchors =\n2 growing reputations." },
      { headline: "Pick one thing.\nGo three times.", body: "Orbit scores your events and\nweights recurring ones on purpose.", footer: "Link in bio" },
    ],
  },
  {
    slug: "05-30-day-rebuild-plan",
    title: "The 30-day social rebuild plan",
    caption: "The full 30-day protocol. Four weeks, one assignment a day, and the only rule that matters: miss a day → continue, never restart.\n\nSave this. Start Monday. Or start tonight.\n\nThe app runs the whole program → link in bio.\n\n" + HT + " #30daychallenge",
    hashtags: ["#adultfriendship", "#30daychallenge", "#selfimprovement"],
    uploadNotes: "The challenge carousel — expect 'day 1' comments; reply to all of them.",
    slides: [
      { headline: "The 30-day\nsocial rebuild plan", body: "One assignment a day.\nNo personality change required." },
      { headline: "Week 1:\nLeave the apartment", body: "Solo public outings. Low-pressure\nevents. One 45-minute stay.\nGoal: motion, not meaning." },
      { headline: "Week 2:\nStart conversations", body: "Ask one question per outing.\nLearn one name. Talk to the\norganizer — they're paid in hellos." },
      { headline: "Week 3:\nFollow up", body: "Send the messages. Invite someone\nto a repeat event. Revive one\ndormant tie — no apology for the gap." },
      { headline: "Week 4:\nBuild cadence", body: "Pick your 1-2 recurring anchors.\nDrop the low-yield stuff.\nPlan next month like training." },
      { headline: "The only rule:\n*never restart*", body: "Missed two days? Continue from\ntoday. Restarting is a trap\ndisguised as discipline.", register: "mirror" },
      { headline: "Day 30 you're not\na new person", body: "You're the same person\nwith a working rhythm.\nThat's the whole point." },
      { headline: "The app runs\nthe entire program", body: "Daily assignments, recovery,\nprogress — private, no feed.", footer: "Join the beta → link in bio" },
    ],
  },
  {
    slug: "06-become-a-regular-how",
    title: "How to become a regular somewhere",
    caption: "“Become a regular” sounds nice. Here's the actual mechanics — the visit-by-visit playbook.\n\n" + HT + " #thirdplace",
    hashtags: ["#adultfriendship", "#community", "#thirdplace"],
    uploadNotes: "Tactical follow-on to carousel 04. Space 1-2 weeks apart.",
    slides: [
      { headline: "How to become\na regular somewhere", body: "The visit-by-visit playbook." },
      { headline: "First: pick the\nright place", body: "Weekly (not monthly).\nSame people attend.\nConversation is possible.\nYou could imagine going 10 times." },
      { headline: "Visit 1: just attend", body: "No networking agenda.\nLearn the rhythm of the thing.\nFind out when it repeats." },
      { headline: "Visit 2: say\n“good to be back”", body: "To anyone who looks familiar —\nstaff, organizer, the person\nwho was there last week." },
      { headline: "Visit 3: names", body: "Learn two. Use them.\nBy now people have noticed\nyou're becoming a fixture." },
      { headline: "Visit 4-5: small\ncontributions", body: "Arrive early, help set up,\nask the organizer what they need.\nHelpers become insiders fast." },
      { headline: "Then: the invitation\nhappens on its own", body: "Regulars get invited to the\nafter-thing. That's not luck —\nit's accumulated familiarity." },
      { headline: "Track your repeat\nexposures", body: "Orbit counts them and nudges\nyou back to your anchors.", footer: "Link in bio" },
    ],
  },
  {
    slug: "07-stop-collecting-events",
    title: "Stop collecting events you never attend",
    register: "mirror",
    caption: "Your saved folder is a museum of intentions.\n\nCollecting options is the most productive-feeling form of avoidance. Here's the pattern — and the one-decision fix.\n\n" + HT,
    hashtags: ["#adultfriendship", "#sociallife", "#procrastination"],
    uploadNotes: "Mirror register. Confrontational-relatable — top comment bait: 'how many events are in YOUR saved folder?'",
    slides: [
      { headline: "Stop collecting events\nyou never attend", body: "A pattern you might recognize." },
      { headline: "Saving feels\nlike progress", body: "Dopamine of a plan,\nzero cost of attendance.\nThat's the trap." },
      { headline: "The saved folder is where\nintentions go to *age*", body: "4 events saved this month.\n0 attended.\nSound familiar?" },
      { headline: "Research is avoidance\nwith a clipboard", body: "One more browse, one more\ncomparison, one more “maybe\nnext week” — all of it feels\nresponsible. None of it is going." },
      { headline: "The one-decision rule", body: "You can't save a new event until\nyou've decided on the last one:\ngoing (pick the date)\nor not (delete it)." },
      { headline: "Options are not action", body: "One committed Tuesday beats\na folder of perfect Saturdays." },
      { headline: "Orbit makes you commit", body: "Interested → planned → attended.\nThe statuses are the point.", footer: "Link in bio" },
    ],
  },
  {
    slug: "08-drained-but-want-out",
    title: "What to do when you want to go out but feel drained",
    caption: "Drained but restless is the most common Friday feeling nobody plans for.\n\nThe answer isn't push through OR stay home. It's the minimum viable outing.\n\nSave this for the next drained Friday.\n\n" + HT + " #introvert",
    hashtags: ["#introvert", "#sociallife", "#selfcare"],
    uploadNotes: "Gentle register. Post on a Friday afternoon.",
    slides: [
      { headline: "Drained, but you still\nwant to get out?", body: "There's a plan size for that." },
      { headline: "The mistake: treating it\nas all-or-nothing", body: "Either the full social night\nor the couch. Both feel wrong.\nBecause both are wrong." },
      { headline: "The answer: the\n*minimum viable outing*", body: "Designed for exactly this state.\nLow effort. Public. Complete." },
      { headline: "Examples that count", body: "Read in a cafe, not your couch.\nSunset walk that ends somewhere public.\nDessert spot you've never tried.\nLibrary evening hours." },
      { headline: "The rules are gentle", body: "No conversation required.\n30-45 minutes.\nLeave whenever you want." },
      { headline: "Why it still matters", body: "It keeps the leaving-the-apartment\nmuscle warm. Drained nights\nhandled well protect the\nmotivated nights." },
      { headline: "Three plans for tonight,\nsized to your energy", body: "Drained → minimum viable.\nThe generator respects the tank.", footer: "Try it → link in bio" },
    ],
  },
  {
    slug: "09-friendship-after-divorce",
    title: "Adult friendship after divorce",
    caption: "Divorce quietly takes the couple-friends with it. Not from malice — from logistics. The dinners were couple-shaped.\n\nThe rebuild is rhythm, not reinvention.\n\n" + HT + " #divorce #startingover",
    hashtags: ["#divorce", "#startingover", "#adultfriendship"],
    uploadNotes: "Empathetic register — moderate comments carefully, never pivot to dating.",
    slides: [
      { headline: "Adult friendship\nafter divorce", body: "The part nobody prepares you for." },
      { headline: "The couple-friends\nleave with the marriage", body: "Not from malice. From logistics.\nThe dinners were couple-shaped.\nThe invites came as a set." },
      { headline: "So you're rebuilding\nfrom scratch at 40+", body: "While everyone your age\nalready has their people.\nIt's not fair. It's just true.", register: "mirror" },
      { headline: "Skip the reinvention\nmontage", body: "You don't need a new personality,\na new wardrobe, or a\n“new chapter” speech." },
      { headline: "You need a rhythm", body: "One recurring event, weekly.\nOne follow-up, weekly.\nOne ordinary outing at a time." },
      { headline: "Private matters here", body: "No feed. No announcing.\nNo performing recovery\nfor an audience." },
      { headline: "Quiet. Repeatable. Yours.", body: "Orbit runs the rhythm —\nnobody sees it but you.", footer: "Join the beta → link in bio" },
    ],
  },
  {
    slug: "10-friends-after-moving",
    title: "Making friends after moving cities",
    caption: "Eight months in and nobody to call — that's the default outcome of a move, not a personal failure.\n\nIntegration is built, not granted. The 90-day protocol:\n\n" + HT + " #newcity",
    hashtags: ["#newcity", "#makingfriends", "#adultfriendship"],
    uploadNotes: "Evergreen search magnet. Also convert to a blog post (SEO cluster 2).",
    slides: [
      { headline: "Making friends after\nmoving cities", body: "The 90-day protocol." },
      { headline: "First, the truth:", body: "Nobody integrates you\nautomatically. The city didn't\nnotice you arrived.", register: "mirror" },
      { headline: "Month 1: pick two\nrecurring anchors", body: "One fitness-ish, one interest-ish.\nWeekly, not monthly.\nAttend both twice." },
      { headline: "Month 2: become\na familiar face", body: "Keep showing up. Learn names.\nSay “good to be back.”\nTalk to the organizers." },
      { headline: "Month 3: convert", body: "One follow-up per week to\nsomeone you've now met twice.\nInvite someone to the thing\nyou already attend." },
      { headline: "What NOT to do", body: "Don't app-hop for strangers.\nDon't try 12 different events.\nDon't wait for work friends\nto materialize." },
      { headline: "90 days of this and\nthe city knows your face", body: "Not a big life. A real one.\nThat's the start." },
      { headline: "Orbit runs the protocol", body: "Anchors, follow-ups, cadence —\ntracked privately.", footer: "Try the 7-day plan → link in bio" },
    ],
  },
  {
    slug: "11-remote-work-social-rhythm",
    title: "Remote work and lost social rhythm",
    caption: "You didn't become antisocial. Your infrastructure disappeared.\n\nThe office was ambient social reps — free, daily, unnoticed. Remote deleted them. Here's what to build instead.\n\n" + HT + " #remotework",
    hashtags: ["#remotework", "#wfh", "#sociallife"],
    uploadNotes: "Big crossover audience. Also strong on LinkedIn as a document post.",
    slides: [
      { headline: "Remote work broke\nyour social rhythm", body: "Quietly. Here's the mechanism." },
      { headline: "The office was ambient\nsocial infrastructure", body: "Hallway hellos. Lunch invites.\nSomeone's birthday cake.\nZero effort. Daily reps." },
      { headline: "You never counted them\nbecause they were free", body: "5-10 micro-interactions a day,\ndelivered by the building." },
      { headline: "Remote deleted them\nwithout a replacement", body: "Slack is not contact.\nMeetings are not conversation.", register: "mirror" },
      { headline: "The fix is *designed*,\nnot wished for", body: "What the office did automatically,\nyou now do deliberately." },
      { headline: "The design:", body: "2 recurring anchors a week.\n1 solo-but-public work session.\n1 follow-up a week.\nThat's the whole replacement." },
      { headline: "Design it once,\nrun it weekly", body: "Orbit is the system that runs it.", footer: "Start with one rep → link in bio" },
    ],
  },
  {
    slug: "12-introvert-social-cadence",
    title: "How introverts can build social cadence",
    caption: "“Just put yourself out there” — out where? For how long? Doing what?\n\nPressure isn't a plan. Structure is. The introvert-native way to build a social life:\n\n" + HT + " #introvert",
    hashtags: ["#introvert", "#introvertlife", "#socialskills"],
    uploadNotes: "Most engaged niche. Pin a comment asking which rule helps most.",
    slides: [
      { headline: "Social cadence\nfor introverts", body: "No personality change required." },
      { headline: "The worst advice:\n“put yourself out there”", body: "Out where? For how long?\nDoing what? Pressure\nisn't a plan.", register: "mirror" },
      { headline: "Rule 1: structured\nbeats open-ended", body: "A class, a club, a volunteer shift —\nthings with a format and an end time.\nMingling is the enemy." },
      { headline: "Rule 2: the exit rule\ngoes in first", body: "“I can leave after 45 minutes”\nis what gets you in the door.\nKnowing the exit makes\nthe entrance possible." },
      { headline: "Rule 3: one micro-goal\nper outing", body: "Ask one question. Learn one name.\nThen you're done — anything\nelse is bonus." },
      { headline: "Rule 4: recurring\nover novel", body: "Familiar rooms cost less energy.\nThe 4th visit to the same place\nis cheaper than the 1st\nvisit anywhere." },
      { headline: "Rule 5: schedule recovery", body: "Social reps cost introverts real\nenergy. Budget the recharge like\npart of the workout." },
      { headline: "A plan sized to your\nenergy, every night", body: "Drained → minimum viable.\nThe generator respects that.", footer: "Try it → link in bio" },
    ],
  },
  {
    slug: "13-72-hour-rule",
    title: "The 72-hour follow-up rule",
    caption: "Timing beats wording. Every time.\n\nThe complete 72-hour rule — with the exact messages that clear the bar.\n\n" + HT + " #followup",
    hashtags: ["#adultfriendship", "#socialskills", "#networking"],
    uploadNotes: "Rule format + scripts = save magnet. Sibling of video 10.",
    slides: [
      { headline: "The 72-hour\nfollow-up rule", body: "Timing beats wording. Every time." },
      { headline: "Met someone good?\nThe clock is running.", body: "Day 1: they remember you clearly.\nDay 3: still warm.\nWeek 2: stranger with shared trivia." },
      { headline: "Why 72 hours works", body: "Soon enough that no\nreintroduction is needed.\nNot so fast it feels eager.\nThe window does the work." },
      { headline: "The message can be\n*five words*", body: "“Good meeting you at run club.”\nDone. The bar is that low\nbecause timing already\ncleared it." },
      { headline: "Add one hook\nif you have one", body: "“I'm going again Thursday —\nyou in?” The recurring event\ndoes the scheduling for you." },
      { headline: "What NOT to send", body: "No essays. No intensity.\nNo “we should definitely\nhang out sometime” —\nthat's where plans go to die.", register: "mirror" },
      { headline: "Then let it breathe", body: "One message. If no reply,\nthe door stays open.\nTwo unanswered = stop." },
      { headline: "Orbit tracks the window\nand drafts the message", body: "You hit send. Always you.", footer: "Link in bio" },
    ],
  },
  {
    slug: "14-options-are-not-action",
    title: "Options are not action",
    register: "mirror",
    caption: "The most productive-feeling way to avoid your own social life: keep improving your options.\n\nOne committed Tuesday beats a folder of perfect Saturdays.\n\n" + HT,
    hashtags: ["#adultfriendship", "#sociallife", "#action"],
    uploadNotes: "Short, punchy, philosophical. Good mid-week slot.",
    slides: [
      { headline: "Options are\nnot action", body: "A short intervention." },
      { headline: "You have the apps.\nThe lists. The tabs.", body: "A research operation any\nanalyst would admire." },
      { headline: "Optionality feels\nlike wealth", body: "Look at everything I *could* do.\nBut unattended options\nexpire worthless.", register: "mirror" },
      { headline: "Meanwhile the calendar\nsays the truth", body: "Saved: 14 events.\nAttended: 1.\nThe gap is the whole story.", register: "mirror" },
      { headline: "One committed Tuesday\nbeats a folder of\nperfect Saturdays", body: "Commitment is the only\nconversion event that matters." },
      { headline: "Tonight: close the tabs.\nPick one. Go.", body: "Orbit exists to force\nexactly this move.", footer: "Link in bio" },
    ],
  },
  {
    slug: "15-how-orbit-works",
    title: "How Orbit works",
    caption: "A private operating system for rebuilding your social life. No feed, no matching, no performing.\n\nHere's the whole product in one carousel. Free beta — link in bio.\n\n" + HT + " #buildinpublic",
    hashtags: ["#adultfriendship", "#buildinpublic", "#indieapp"],
    uploadNotes: "The product carousel. Post AFTER audience-building content has run 2+ weeks.",
    slides: [
      { headline: "How *Orbit* works", body: "A private system for rebuilding\nyour social life. 8 slides." },
      { headline: "Tonight", body: "Three plans matched to your mood,\nenergy, and budget — minimum\nviable, standard, bold.\nThe easy one still counts." },
      { headline: "Events, scored", body: "Recurring, conversation-friendly\nevents rise to the top. Arrival\nstrategy, openers, and an exit rule\nfor each one." },
      { headline: "People, tracked privately", body: "Who you met, where, and whether\nthe tie is drifting. A reality check\nthat tells you when to invest\nand when to stop." },
      { headline: "Follow-ups, drafted", body: "Six tones, a why-it-works, and an\nhonest risk level. You send it from\nyour own apps — Orbit never\nsends anything." },
      { headline: "Reps, counted", body: "Left the apartment. Asked one\nquestion. Sent one follow-up.\nA training log, not a game." },
      { headline: "What it will never be", body: "No feed. No profiles. No matching.\nNo AI companion. Your data stays\non your device." },
      { headline: "The 30-day rebuild\nruns on top", body: "Four weeks: leave the apartment,\nstart conversations, follow up,\nbuild cadence." },
      { headline: "Free beta. No account.", body: "Two minutes to your\nfirst 7-day plan.", footer: "Link in bio" },
    ],
  },
];
