// 20 Facebook group-ready posts across the 8 required categories. Each has:
// main post, softer version, short version, DM response, beta-qualification
// question, privacy note, CTA. Group posting rules vary wildly — the
// "softer" version exists for stricter groups.

const PRIVACY = "Everything stays in your browser — no account, no contact import, it never reads or sends your messages.";
const DM = (angle) => `Hey! Thanks for the interest. ${angle} It's free, no account needed — here's the link: [LINK]. One ask: after a few days, tell me the single most annoying thing about it. That's genuinely the most helpful feedback. ${PRIVACY}`;
const QUALIFY = "Quick question so I send this to the right people: what's the step that usually breaks for you — deciding to go out, actually going, or following up with people after?";

export const facebook = [
  // --- New city (3) ---
  {
    slug: "fb01-newcity-8months",
    category: "new-city",
    main: `Moved here a while back and finally admitted something: the city wasn't going to integrate me automatically. Eight months of "it'll happen naturally" produced approximately nothing — what worked was embarrassingly mechanical: two recurring events attended weekly, plus actually texting people I met within a few days.\n\nI ended up building a small private app around that loop (plans your night, tracks who you met, drafts the follow-up text). If anyone else here is in the "know the city, don't know anyone" phase, I'm looking for a few people to test it — free, no account. Comment or DM.`,
    softer: `For anyone in the "moved here months ago, still don't really know anyone" phase — the thing that finally worked for me was mechanical, not magical: two recurring events weekly + following up with people within a few days. Happy to share the little tool I built around it if anyone wants (free) — but honestly the two-anchor rule alone is the advice.`,
    short: `New-ish to the city and social life not materializing? Two recurring events weekly + follow-ups within 72 hours. I built a small free tool around this loop — DM if you want to test it.`,
    dm: DM("It's a private system for the go-out → follow-up → repeat loop, tuned for exactly the new-city situation."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "DM me 'testing' and I'll send the link.",
  },
  {
    slug: "fb02-newcity-anchors-ask",
    category: "new-city",
    main: `Question for the group: what are the actually-good RECURRING events here? Not one-off festivals — the weekly/biweekly things where the same people show up: run clubs, board game nights, community gatherings, classes.\n\nAsking because repeated exposure is the whole trick to going from "new here" to "has people" — and the recurring inventory is weirdly hard to find on the big event apps. I'll compile answers into a list and repost for everyone.`,
    softer: `What weekly/recurring things do people here swear by — run clubs, game nights, classes, community gatherings? Compiling a list for fellow newcomers, will share back.`,
    short: `Best RECURRING (weekly-ish) events in the area? Compiling a newcomer list, will post it back here.`,
    dm: DM("Since you're into the recurring-events thing — the app scores events and deliberately weights recurring ones, because that's where friendships actually form."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment your recurring anchor — I'll compile and repost.",
  },
  {
    slug: "fb03-newcity-honest",
    category: "new-city",
    main: `Honest one: does anyone else find that the hard part isn't FINDING things to do here, it's the follow-through? I have a saved-events folder that could power a small city's cultural calendar and an attendance record that could not.\n\nWhat finally moved the needle for me was one dumb rule: no saving a new event until I've decided on the last one. Curious what rules/tricks work for others.`,
    softer: `The saved-events-never-attended folder: just me? What actually gets you from "saved" to "went"?`,
    short: `Saved events: 14. Attended: 1. What's your trick for closing that gap?`,
    dm: DM("The app is basically that one-decision rule with infrastructure — it makes you commit events to 'planned' instead of hoarding 'interested.'"),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Share your trick in the comments.",
  },

  // --- Adult friendship (3) ---
  {
    slug: "fb04-friendship-secondinteraction",
    category: "adult-friendship",
    main: `Something I keep coming back to: most adult friendships don't fail dramatically. They just never get a second interaction. We meet someone good, both say "we should hang out," and both wait for the other to text.\n\nI got tired of losing people that way and built a small private tool that tracks who I met and nags me (kindly) to follow up within 72 hours. It's changed more than I expected. Looking for a few people to beta test — free, private, no account.`,
    softer: `Most adult friendships don't fail — they just never get a second interaction. The 72-hour follow-up window is real. If you take nothing else from this post: text the person you met last week. Five words is enough.`,
    short: `The friendship didn't fail. It never got a second interaction. Text the person you met last week — 72-hour window is real.`,
    dm: DM("It's the follow-up half that's the core: it tracks who you met and drafts the message in your voice — you always hit send yourself."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "DM 'testing' for the link.",
  },
  {
    slug: "fb05-friendship-regular",
    category: "adult-friendship",
    main: `The best adult-friendship advice I've ever gotten fits in four words: become a regular somewhere.\n\nSame place, weekly. Visit 1 you're a stranger, visit 2 you're familiar, visit 3 people expect you — and expected people get invited to things. It's not charisma, it's attendance.\n\nWhere did "becoming a regular" work for you? (And if you want the little app I built to track repeat visits and follow-ups, DM me — free beta.)`,
    softer: `Four-word friendship advice: become a regular somewhere. Visit 3 is when people start expecting you — and expected people get invited to things. Where has this worked for you?`,
    short: `Become a regular somewhere. Visit 3 = people expect you. Expected people get invited to things. That's the whole cheat code.`,
    dm: DM("It scores your events and deliberately pushes recurring ones — becoming a regular is basically the app's thesis."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment where you're a regular — genuinely curious.",
  },
  {
    slug: "fb06-friendship-35",
    category: "over-30-social",
    main: `Making friends after 35 isn't emotionally hard — it's operationally annoying. Everyone's calendar is full, everyone's default is home, and nothing repeats unless someone MAKES it repeat.\n\nWhich means it's an operations problem, and operations problems have systems: a weekly anchor event, a follow-up habit, one invitation a week. Boring. Works.\n\nI built a private app that runs exactly this system — looking for a few 35+ testers who'll tell me where it feels off. Free, no account, comment or DM.`,
    softer: `Friendship after 35 is an operations problem, not a personality problem: one weekly anchor event, one follow-up a week, one invitation a week. Boring. Works.`,
    short: `Friendship after 35: not emotionally hard, operationally annoying. The fix is a system, not a personality change.`,
    dm: DM("It's built for exactly the full-calendar 35+ situation — small weekly reps, not a lifestyle overhaul."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "DM 'testing' if you want in.",
  },

  // --- Divorce recovery (2) — extra care, softest versions lead ---
  {
    slug: "fb07-divorce-couplefriends",
    category: "divorce-recovery",
    main: `Something nobody warned me about: the social life was couple-shaped. The dinners, the trips, the standing plans — they came as a set, and after the divorce the logistics just quietly stopped including me. No malice anywhere. Still brutal.\n\nWhat's helped is treating the rebuild as rhythm, not reinvention: one recurring thing weekly, one follow-up to someone new weekly, no announcements, no "new chapter" performance. Slow and unglamorous and it's working.\n\nSharing in case the frame helps someone else in the rebuild phase.`,
    softer: `For anyone rebuilding socially after divorce: the frame that helped me was "rhythm, not reinvention." One recurring event weekly. One follow-up weekly. No performance, no announcements. Slow, unglamorous, working.`,
    short: `Post-divorce social rebuild: rhythm, not reinvention. One recurring event + one follow-up, weekly. That's the whole program.`,
    dm: DM("Gently on this one: it's a private tracker/planner, absolutely not a dating thing — it just keeps the weekly rhythm going without any audience."),
    qualify: "No qualification question in divorce groups — if someone asks for the tool, just share it kindly.",
    privacy: PRIVACY + " There is no feed and no visibility to anyone — that matters extra here.",
    cta: "None in-post. Only respond if asked. Support groups are not funnels.",
  },
  {
    slug: "fb08-divorce-fortyplus",
    category: "divorce-recovery",
    main: `Rebuilding a social life from scratch at 40+ while everyone your age already "has their people" is a specific kind of hard that doesn't get talked about enough.\n\nIf you're in it: the math that helped me — you don't need a circle, you need two anchors and a follow-up habit. A weekly thing where people learn your face, and the discipline to text the good ones within a few days. The circle assembles itself later.\n\nSolidarity to anyone mid-rebuild.`,
    softer: `Rebuilding at 40+ when everyone already has their people: you don't need a circle. You need two weekly anchors and a follow-up habit. The circle assembles itself later. Solidarity to anyone mid-rebuild.`,
    short: `You don't need a circle. Two weekly anchors + a follow-up habit. The circle assembles itself later.`,
    dm: DM("Since you asked — it's the private system I use for the anchors + follow-up rhythm."),
    qualify: "None — see fb07 note.",
    privacy: PRIVACY,
    cta: "None in-post — support-first.",
  },

  // --- Introverts (3) ---
  {
    slug: "fb09-introvert-exitrule",
    category: "introverts",
    main: `The single best thing I've done for my social life as an introvert: deciding the EXIT before the entrance. "I'm allowed to leave after 45 minutes, no guilt" is what gets me through the door — and most nights I stay longer anyway, because the trap feeling is gone.\n\nI built this (plus one micro-goal per outing, plus energy-sized plans) into a little private app. Looking for introvert testers who'll tell me if it still secretly pushes too hard. Free, no account.`,
    softer: `Introvert tip that changed my attendance rate: decide the exit before the entrance. "Allowed to leave after 45 minutes, zero guilt." Knowing the way out is what gets you in. Most nights you'll stay anyway.`,
    short: `Decide the exit before the entrance: "allowed to leave after 45 min, no guilt." That's what gets introverts through the door.`,
    dm: DM("Every plan it generates comes with an exit rule and one micro-goal — it's introvert-native by design."),
    qualify: "So I match you right: are you more 'drained by events' or 'fine at events, drained by open-ended mingling'?",
    privacy: PRIVACY,
    cta: "DM 'testing' — 5 spots this round.",
  },
  {
    slug: "fb10-introvert-mvo",
    category: "introverts",
    main: `Public service announcement for the drained-but-restless: the minimum viable outing counts. Reading at a cafe instead of your couch counts. A sunset walk that ends somewhere public counts. 45 minutes at a low-key event counts.\n\nThe all-or-nothing frame (Whole Social Night vs. couch) is what keeps us home. Shrink the unit until it's doable, then actually do it.\n\nWhat's your go-to minimum viable outing?`,
    softer: `Drained but restless? The minimum viable outing counts: cafe with your book, walk that ends somewhere public, 45 min at something low-key. Shrink the unit until it's doable. What's yours?`,
    short: `The minimum viable outing counts. Cafe + book counts. Shrink the unit until it's doable.`,
    dm: DM("The Solo Night Generator has a 'minimum viable' tier for exactly this state — drained input, gentle plan out."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment your go-to MVO.",
  },
  {
    slug: "fb11-introvert-structured",
    category: "introverts",
    main: `Hot take from a fellow introvert: we're not bad at socializing, we're bad at UNSTRUCTURED socializing. Put me at a party and I'm furniture; put me at a board game night, a class, or a volunteer shift and I'm fine — the format does the social heavy lifting.\n\nIf you keep bouncing off events, the fix might not be courage. It might be picking structured ones: defined activity, defined end time, built-in things to talk about.\n\nWhat structured settings work for you?`,
    softer: `Introverts aren't bad at socializing — we're bad at UNSTRUCTURED socializing. Board game night > party, every time. The format does the heavy lifting. What structured settings work for you?`,
    short: `Introverts: the fix isn't courage, it's structure. Board game night > party. The format does the heavy lifting.`,
    dm: DM("Event scoring in the app rates 'social difficulty' and conversation potential — structured settings score exactly how you'd hope."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment your best structured setting.",
  },

  // --- Remote workers (3) ---
  {
    slug: "fb12-remote-infrastructure",
    category: "remote-workers",
    main: `Remote work realization that took me way too long: the office wasn't just where I worked — it was my ambient social infrastructure. Hallway hellos, lunch invites, birthday cake. Five to ten free micro-interactions a day, and I never counted them until they were gone.\n\nNothing replaces them automatically. You have to design the replacement: I do two recurring evening anchors a week + one solo-but-public work session + one follow-up text a week. That's the whole system and it works.\n\nWhat did you build to replace the office's social side?`,
    softer: `The office was ambient social infrastructure — 5-10 free micro-interactions a day. Remote deleted them. The replacement has to be designed: recurring anchors, public work sessions, deliberate follow-ups. What did you build?`,
    short: `The office was free daily social reps. Remote deleted them. What did you design as the replacement?`,
    dm: DM("It's basically the designed replacement in app form — weekly anchors, reps, and follow-ups tracked privately."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment what you've built — collecting real systems.",
  },
  {
    slug: "fb13-remote-3day-streak",
    category: "remote-workers",
    main: `Fellow remote workers: what's your record for consecutive days without a real in-person conversation (delivery people don't count)? Mine was embarrassing enough to make me build a tracking system.\n\nNot a guilt post — a math post. If the number is greater than 3 regularly, the fix is one scheduled recurring thing per week. Not more willpower. Scheduling.`,
    softer: `Remote workers: how many days in a row without a real in-person conversation? If it's regularly 3+, the fix is one scheduled weekly thing — not willpower, scheduling.`,
    short: `Days without a real in-person conversation: if regularly 3+, schedule one weekly anchor. Scheduling beats willpower.`,
    dm: DM("The rep tracker counts exactly this — and the weekly plan makes sure the streak of zero-people days breaks by design."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Drop your (honest) number in the comments.",
  },
  {
    slug: "fb14-remote-coworking-myth",
    category: "remote-workers",
    main: `Unpopular remote-work opinion: coworking spaces don't fix the social problem. You just do your Zoom calls near strangers instead of alone.\n\nWhat fixes it: things with conversation built into the format — a run club, a class, a weekly game night, a volunteer shift. The office's social magic wasn't proximity, it was REPEATED proximity with the same people plus a reason to talk.\n\nAgree/disagree? Has coworking actually produced friends for anyone here?`,
    softer: `Coworking = doing Zoom calls near strangers. The office's magic wasn't proximity — it was repeated proximity + a reason to talk. That's what to rebuild: run club, class, game night, volunteer shift.`,
    short: `Coworking isn't the fix — repeated proximity + a reason to talk is. Run club > hot desk.`,
    dm: DM("The event scoring is built on exactly this: repeat potential + conversation potential outrank everything else."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Agree/disagree in comments.",
  },

  // --- Local NYC/JC (2) ---
  {
    slug: "fb15-jc-recurring-list",
    category: "local-nyc-jc",
    main: `Jersey City: compiling the definitive list of RECURRING social things — weekly run clubs, game nights, community gatherings, classes, volunteer shifts. The stuff where the same faces show up and you can actually become a regular.\n\nDrop yours below (day of week + neighborhood helps). I'll organize and repost the full list for everyone. JSQ/Grove/downtown/Heights all welcome.`,
    softer: `JC: what recurring weekly things do you actually attend — run clubs, game nights, community events? Compiling a list to share back.`,
    short: `JC recurring events (weekly, same-faces stuff): drop yours + day + neighborhood. Compiling for the group.`,
    dm: DM("Local bonus: the app ships with a JC/NYC seed pack — run club, community nights, game nights — and I'd love local testers to sanity-check it."),
    qualify: "Which neighborhood are you based in? (Helps me match the seed data.)",
    privacy: PRIVACY,
    cta: "Comment your anchor. List gets reposted Friday.",
  },
  {
    slug: "fb16-nyc-transplant",
    category: "local-nyc-jc",
    main: `NYC has the weirdest social math in America: 8 million people, hardest place to feel known. The city's size is exactly why the become-a-regular strategy matters MORE here, not less — you have to shrink the city to a few rooms where your face repeats.\n\nTwo anchors (one near home, one near work/transit), weekly, plus 72-hour follow-ups. Ninety days and your version of NYC has people in it.\n\nTransplants: what shrunk the city for you?`,
    softer: `NYC: 8 million people, hardest place to feel known. The fix is shrinking the city to a few rooms where your face repeats — two weekly anchors + follow-ups. What shrunk NYC for you?`,
    short: `NYC social math: shrink 8 million people to 2 rooms where your face repeats weekly. That's the whole strategy.`,
    dm: DM("The app's whole scoring system is built around exactly this — recurring anchors over infinite novelty."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment what shrunk the city for you.",
  },

  // --- Over-30 social groups (2) ---
  {
    slug: "fb17-over30-nobar",
    category: "over-30-social",
    main: `Over-30 social life confession: I aged out of nightlife but nobody handed me the replacement playbook. Turns out it's: morning run clubs, board game nights, volunteer shifts, community dinners, classes — the stuff where conversation doesn't require shouting.\n\nThe underrated part? These settings are all RECURRING, which is exactly what friendship needs anyway. Nightlife was novelty; this stuff compounds.\n\nWhat's in your post-nightlife playbook?`,
    softer: `Aged out of nightlife, nobody handed me the replacement playbook. Turns out: run clubs, game nights, volunteer shifts, community dinners. All recurring — which is what friendship needed anyway. What's in your playbook?`,
    short: `Post-nightlife playbook: run clubs, game nights, volunteer shifts, community dinners. Recurring > loud. What's yours?`,
    dm: DM("Zero of the app's suggestions center bars/nightlife — it's built for exactly the post-nightlife playbook."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Comment your playbook additions.",
  },
  {
    slug: "fb18-over30-invite",
    category: "over-30-social",
    main: `The highest-leverage social move over 30, and almost nobody does it: inviting someone to a thing you're ALREADY attending. "I'm going Thursday — come through" costs you nothing (the plan exists), carries no rejection weight (you're going anyway), and it's how acquaintances become friends.\n\nChallenge for the week: one zero-cost invitation. Report back.`,
    softer: `Highest-leverage social move: invite someone to a thing you're already attending. "I'm going Thursday — come through." Zero cost, zero rejection weight. One invitation this week — report back.`,
    short: `"I'm going Thursday — come through" is a complete invitation. One this week. Report back.`,
    dm: DM("The weekly review literally assigns this — one invitation a week to a weak tie worth nurturing."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Report back in the comments when you've sent one.",
  },

  // --- Community/event groups (2) ---
  {
    slug: "fb19-organizers-thanks",
    category: "community-event-groups",
    main: `To the people who ORGANIZE the recurring stuff — run clubs, game nights, community dinners: you're quietly running the social infrastructure of this whole area, and the "how was your week" you give newcomers matters more than you know.\n\nQuestion for organizers: what makes a newcomer stick? What do the ones who become regulars do differently on visits 1-3? (Building something to help newcomers stick, and your view of the pattern is gold.)`,
    softer: `Organizers of recurring events: what makes a newcomer stick vs. vanish? What do future-regulars do differently on visits 1-3? Genuinely curious about the pattern from your side.`,
    short: `Event organizers: what do the newcomers who STICK do differently on visits 1-3?`,
    dm: DM("I'm building the newcomer-side tool — arrival strategies, one micro-goal per visit, return nudges. Organizer input shapes it."),
    qualify: "Do you organize something recurring? What/where — and does it need more regulars?",
    privacy: PRIVACY,
    cta: "Organizer answers especially wanted below.",
  },
  {
    slug: "fb20-community-first-timer",
    category: "community-event-groups",
    main: `A note for anyone who almost came to a community event this week and bailed at the door (or the couch): the gap between "almost went" and "went" is smaller than it feels, and everyone inside was a first-timer once.\n\nPractical version: arrive in the first third, get whatever there is to hold (coffee, program, name tag), ask one person how they found the thing. Then you're allowed to leave. That's a complete first visit.\n\nSee you at the next one.`,
    softer: `To anyone who almost came and bailed: arrive early-ish, hold something (coffee counts), ask one person how they found it. Then you can leave. That's a complete first visit. See you at the next one.`,
    short: `First-visit formula: arrive early-ish, hold a coffee, ask one person how they found it. Then you're free. That counts.`,
    dm: DM("The app generates exactly these arrival strategies + one micro-goal per event."),
    qualify: QUALIFY,
    privacy: PRIVACY,
    cta: "Tag someone who keeps saying 'next time.'",
  },
];
