// 20 short-form video packages. Scenes render as timed text frames
// (1080x1920). *word* = accent highlight. register:"mirror" = clay accent
// for hard-truth content. Sum of seconds ≈ 22-40s per video.

const HT = {
  core: ["#adultfriendship", "#makingfriends", "#sociallife"],
  intro: ["#introvert", "#introvertlife"],
  city: ["#newcity", "#movingout"],
  remote: ["#remotework", "#wfh"],
  divorce: ["#divorce", "#startingover"],
  habit: ["#selfimprovement", "#habits"],
};

const YT_FOOT = `
Orbit is a private system for rebuilding your social life: weekly outings, follow-up drafts, and a tracker for the people worth staying in touch with. No feed, no matching, no performing. Free to try — link in the pinned comment.

Not a dating app. Not therapy. Just the loop: go out, talk to one person, follow up, repeat.`;

export const videos = [
  {
    slug: "01-friendship-is-follow-up",
    title: "Adult friendship is mostly follow-up",
    thumbnailTitle: "Adult friendship is mostly *follow-up*",
    cta: "Try the 7-day plan.",
    scenes: [
      { text: "Nobody tells you this about\nmaking friends after 30.", seconds: 3.5, big: true },
      { text: "It's not charisma.\nIt's not confidence.", seconds: 3 },
      { text: "It's *follow-up*.", seconds: 2.5, big: true },
      { text: "You already meet people\nyou like.", sub: "At work. At the gym. At events.", seconds: 3.5 },
      { text: "Then you both say\n“we should hang out”", sub: "and neither of you texts.", seconds: 4, register: "mirror" },
      { text: "The friendship didn't fail.", sub: "It just never got a *second interaction*.", seconds: 4 },
      { text: "Send one message this week\nto someone you already met.", sub: "That's the whole skill.", seconds: 4.5 },
      { text: "Try the *7-day plan*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "Nobody tells you this about making friends after thirty. It's not charisma, and it's not confidence. It's follow-up. You already meet people you like — at work, at the gym, at events. Then you both say 'we should hang out,' and neither of you texts. The friendship didn't fail. It just never got a second interaction. Send one message this week to someone you already met. That's the whole skill.",
    captions: {
      generic: "Adult friendship is mostly logistics and repetition. The message you don't send is where it dies. Try the 7-day plan — link in bio.",
      tiktok: "the friendship didn't fail. it just never got a second interaction. #fyp",
      instagram: "You don't need more charisma. You need to send the text.\n\nAdult friendship is mostly logistics and repetition — and follow-up is the rep almost everyone skips. One message this week to someone you already met. That's the whole assignment.\n\nTry the 7-day plan → link in bio.",
    },
    ytTitle: "Adult friendship is mostly follow-up (nobody tells you this)",
    ytDescription: "Why the friendships you want keep dying quietly — and the one small skill that fixes it." + YT_FOOT,
    hashtags: [...HT.core, "#followup", "#friendship"],
    uploadNotes: "Add trending calm/lofi audio in-app. Post Tue–Thu 6–9pm ET. Pin a comment with the link. This is the flagship insight — post first.",
  },
  {
    slug: "02-need-a-loop-not-events",
    title: "You don't need more events. You need a loop.",
    thumbnailTitle: "You don't need more events.\nYou need a *loop*.",
    cta: "Try the 7-day plan.",
    scenes: [
      { text: "You don't need\nmore event options.", seconds: 3, big: true },
      { text: "You have Meetup.\nYou have Eventbrite.\nYou have 12 open tabs.", seconds: 4 },
      { text: "And you're still home\non Friday night.", seconds: 3, register: "mirror" },
      { text: "Because discovery\nwas never the problem.", seconds: 3 },
      { text: "You need a *loop*:", sub: "Pick one thing. Go. Talk to one person.\nFollow up. *Repeat*.", seconds: 5.5 },
      { text: "Run the loop weekly\nand a social life compounds.", sub: "Browse events nightly and nothing does.", seconds: 5 },
      { text: "Try the *7-day plan*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "You don't need more event options. You have Meetup, you have Eventbrite, you have twelve open tabs — and you're still home on Friday night. Because discovery was never the problem. You need a loop: pick one thing, go, talk to one person, follow up, repeat. Run that loop weekly and a social life compounds. Browse events nightly and nothing does.",
    captions: {
      generic: "Discovery was never the problem. The loop is: pick one, go, talk to one person, follow up, repeat. Link in bio.",
      tiktok: "12 open tabs and still home on friday. the problem isn't options. #fyp",
      instagram: "More options won't fix it. A loop will.\n\nPick something worth attending. Leave the apartment. Talk to one person. Follow up. Repeat. That's the entire system — and running it weekly beats browsing nightly.\n\nStart your 7-day plan → link in bio.",
    },
    ytTitle: "Why more events won't fix your social life",
    ytDescription: "Event apps solved discovery. Nobody solved follow-through. Here's the loop that does." + YT_FOOT,
    hashtags: [...HT.core, "#meetup", "#weekend"],
    uploadNotes: "Strong hook video — good second post. Works with upbeat minimal audio.",
  },
  {
    slug: "03-weak-ties-die",
    title: "Weak ties die without follow-up",
    thumbnailTitle: "*Weak ties* die\nwithout follow-up",
    cta: "Start with one social rep.",
    register: "mirror",
    scenes: [
      { text: "The person you clicked with\nlast week?", seconds: 3, big: true },
      { text: "They're not going to\nfollow up with you.", seconds: 3.5, register: "mirror" },
      { text: "Not because they don't like you.", sub: "Because they're doing what you're doing:\nassuming it'll happen on its own.", seconds: 5 },
      { text: "Weak ties have a *half-life*.", sub: "Every silent week cuts the odds.", seconds: 4 },
      { text: "One low-pressure message.", sub: "“Good meeting you. I'm going again\nnext week — you in?”", seconds: 5 },
      { text: "That's it. That's how\nacquaintances become friends.", seconds: 4 },
      { text: "Start with *one social rep*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "The person you clicked with last week? They're not going to follow up with you. Not because they don't like you — because they're doing exactly what you're doing: assuming it'll happen on its own. Weak ties have a half-life. Every silent week cuts the odds. One low-pressure message: 'Good meeting you. I'm going again next week — you in?' That's it. That's how acquaintances become friends.",
    captions: {
      generic: "Weak ties have a half-life. One low-pressure message keeps them alive. Link in bio.",
      tiktok: "they're not going to text first. neither are you. that's the problem. #fyp",
      instagram: "The connection didn't die dramatically. It just went quiet.\n\nWeak ties have a half-life — every silent week cuts the odds the friendship happens. The fix is one low-pressure message, not a perfect one.\n\nStart with one social rep → link in bio.",
    },
    ytTitle: "Weak ties die without follow-up — here's the 1-message fix",
    ytDescription: "The person you met isn't going to text first. The math of weak ties, and the message that keeps them alive." + YT_FOOT,
    hashtags: [...HT.core, "#weakties", "#networking"],
    uploadNotes: "Clay/mirror register — harder truth, quieter audio. Performs well as a duet/stitch target.",
  },
  {
    slug: "04-become-a-regular",
    title: "Become a regular somewhere",
    thumbnailTitle: "Become a *regular*\nsomewhere",
    cta: "Save this for Friday night.",
    scenes: [
      { text: "The closest thing adult friendship\nhas to a cheat code:", seconds: 4, big: true },
      { text: "*Become a regular* somewhere.", seconds: 3, big: true },
      { text: "Same run club.\nSame class.\nSame community night.", sub: "Weekly.", seconds: 4 },
      { text: "Visit one: you're a stranger.\nVisit two: you're familiar.", seconds: 4 },
      { text: "Visit three: people expect you.", sub: "And expected people get invited to things.", seconds: 4.5 },
      { text: "Novelty feels productive.\n*Repetition* actually works.", seconds: 4 },
      { text: "Pick your place this week.", sub: "Save this for Friday night.", seconds: 3.5 },
    ],
    voiceover: "The closest thing adult friendship has to a cheat code: become a regular somewhere. Same run club, same class, same community night — weekly. Visit one, you're a stranger. Visit two, you're familiar. Visit three, people expect you. And expected people get invited to things. Novelty feels productive. Repetition actually works. Pick your place this week.",
    captions: {
      generic: "Visit three is when people start expecting you. Expected people get invited to things. Pick your place.",
      tiktok: "the cheat code is showing up to the same thing 3 times #fyp",
      instagram: "Stop optimizing for interesting. Optimize for repeated.\n\nThe third visit to the same recurring event is where familiarity starts paying — staff know you, regulars nod at you, and being a familiar face is the actual on-ramp to friendship.\n\nSave this for Friday night.",
    },
    ytTitle: "Become a regular somewhere (the adult friendship cheat code)",
    ytDescription: "Why the third visit to the same place beats ten first visits to new ones." + YT_FOOT,
    hashtags: [...HT.core, "#thirdplace", "#community"],
    uploadNotes: "Highest save-potential video. Caption CTA is 'save this' — don't swap it for a link CTA.",
  },
  {
    slug: "05-second-interaction",
    title: "The second interaction is where friendship begins",
    thumbnailTitle: "The *second interaction*\nis where friendship begins",
    cta: "Try the 7-day plan.",
    scenes: [
      { text: "Unpopular opinion:", sub: "meeting people is the easy part.", seconds: 3.5, big: true },
      { text: "You've met hundreds of people\nyou never saw again.", seconds: 3.5 },
      { text: "First interactions are cheap.", sub: "Everyone's friendly at an event.", seconds: 3.5 },
      { text: "The *second interaction*\nis the rare one.", sub: "It says: that wasn't an accident.", seconds: 4.5 },
      { text: "So stop optimizing for\nmeeting more people.", seconds: 3.5 },
      { text: "Optimize for seeing\nthe same person *twice*.", seconds: 3.5 },
      { text: "Try the *7-day plan*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "Unpopular opinion: meeting people is the easy part. You've met hundreds of people you never saw again. First interactions are cheap — everyone's friendly at an event. The second interaction is the rare one. It says: that wasn't an accident. So stop optimizing for meeting more people. Optimize for seeing the same person twice.",
    captions: {
      generic: "First interactions are cheap. The second one says: that wasn't an accident. Optimize for twice.",
      tiktok: "you've met hundreds of people you never saw again. the second time is the whole game #fyp",
      instagram: "Meeting people was never your problem.\n\nThe second interaction — the one that says 'that wasn't an accident' — is where adult friendship actually begins. Everything in your social life should be engineered toward it: recurring events, follow-ups, invitations.\n\nTry the 7-day plan → link in bio.",
    },
    ytTitle: "The second interaction is where adult friendship begins",
    ytDescription: "Why meeting more people won't help, and engineering the second interaction will." + YT_FOOT,
    hashtags: [...HT.core, "#socialskills"],
    uploadNotes: "Pairs with video 04 — post within same week for a coherent thread.",
  },
  {
    slug: "06-stop-collecting-events",
    title: "Stop collecting events you will never attend",
    thumbnailTitle: "Stop *collecting* events\nyou'll never attend",
    cta: "Link in bio.",
    register: "mirror",
    scenes: [
      { text: "Be honest.", seconds: 2, big: true },
      { text: "How many events are saved\non your phone right now?", seconds: 3.5 },
      { text: "Saving feels like progress.", sub: "It's not. It's *research cosplay*.", seconds: 4, register: "mirror" },
      { text: "You added 4 events this month\nand attended none.", sub: "The list is where intentions go to age.", seconds: 5, register: "mirror" },
      { text: "New rule: you can't save an event\nwithout deciding on the last one.", seconds: 4.5 },
      { text: "One decision beats\nten bookmarks.", seconds: 3.5 },
      { text: "Link in bio.", sub: "Orbit makes you commit to one.", seconds: 3 },
    ],
    voiceover: "Be honest. How many events are saved on your phone right now? Saving feels like progress. It's not — it's research cosplay. You added four events this month and attended none. The list is where intentions go to age. New rule: you can't save an event without deciding on the last one. One decision beats ten bookmarks.",
    captions: {
      generic: "Saving events feels like progress. It's research cosplay. One decision beats ten bookmarks.",
      tiktok: "your saved events folder is a museum of intentions #fyp",
      instagram: "The saved folder isn't a plan. It's a museum of intentions.\n\nCollecting options is the most productive-feeling way to avoid going out. The fix isn't better research — it's one decision, made before the resistance wins.\n\nOrbit makes you pick one → link in bio.",
    },
    ytTitle: "Stop collecting events you'll never attend",
    ytDescription: "Saving isn't planning. Why option-collecting is avoidance wearing a productivity costume." + YT_FOOT,
    hashtags: [...HT.core, ...HT.habit],
    uploadNotes: "Confrontational-relatable — expect 'called out' comments; reply with the one-decision rule, not the product.",
  },
  {
    slug: "07-one-decision-weekend",
    title: "Your weekend needs one decision, not more research",
    thumbnailTitle: "Your weekend needs\n*one decision*",
    cta: "Try the Solo Night Generator.",
    scenes: [
      { text: "Your weekend does not\nneed more research.", seconds: 3.5, big: true },
      { text: "It needs *one decision*.", seconds: 3, big: true },
      { text: "Not the perfect event.\nNot the optimal plan.", seconds: 3.5 },
      { text: "One thing, chosen by 6pm,\nthat gets you out the door.", seconds: 4 },
      { text: "The bar is low on purpose:", sub: "a coffee shop with your book *counts*.\nA 45-minute event *counts*.", seconds: 5 },
      { text: "Decide once. Go.\nLet the night be ordinary.", seconds: 4 },
      { text: "Try the *Solo Night Generator*.", sub: "Three plans in ten seconds. Link in bio.", seconds: 3.5 },
    ],
    voiceover: "Your weekend does not need more research. It needs one decision. Not the perfect event, not the optimal plan. One thing, chosen by six pm, that gets you out the door. The bar is low on purpose: a coffee shop with your book counts. A forty-five minute event counts. Decide once. Go. Let the night be ordinary.",
    captions: {
      generic: "Decide by 6pm. Go. Let the night be ordinary. That's the whole strategy.",
      tiktok: "stop researching your weekend like it's a thesis. one decision. #fyp",
      instagram: "Perfectionism about your weekend is just avoidance with better branding.\n\nOne decision by 6pm beats three hours of browsing. And the ordinary night out — coffee shop, bookstore event, a walk that ends somewhere public — counts completely.\n\nTry the Solo Night Generator → link in bio.",
    },
    ytTitle: "Your weekend needs one decision, not more research",
    ytDescription: "The 6pm rule: decide once, go, let the night be ordinary." + YT_FOOT,
    hashtags: [...HT.core, "#weekend", "#solodate"],
    uploadNotes: "Post Friday 3–5pm — the exact moment the audience is deciding whether to go out.",
  },
  {
    slug: "08-reps-not-motivation",
    title: "Social life needs reps, not motivation",
    thumbnailTitle: "Social life needs *reps*,\nnot motivation",
    cta: "Start with one social rep.",
    scenes: [
      { text: "You don't wait to feel like running\nbefore you train.", seconds: 4, big: true },
      { text: "So why are you waiting\nto *feel social*?", seconds: 3.5 },
      { text: "The feeling follows the rep.", sub: "Not the other way around.", seconds: 4 },
      { text: "A rep is small:", sub: "Left the apartment. Asked one question.\nStayed 45 minutes. Sent one follow-up.", seconds: 5.5 },
      { text: "Track them like training.", sub: "Because that's what this is.", seconds: 4 },
      { text: "Start with *one social rep* today.", sub: "Link in bio.", seconds: 3.5 },
    ],
    voiceover: "You don't wait to feel like running before you train. So why are you waiting to feel social? The feeling follows the rep, not the other way around. A rep is small: left the apartment. Asked one question. Stayed forty-five minutes. Sent one follow-up. Track them like training — because that's what this is.",
    captions: {
      generic: "The feeling follows the rep. Not the other way around. Start with one today.",
      tiktok: "waiting to feel social is like waiting to feel like the gym #fyp",
      instagram: "Motivation is not coming. The rep works anyway.\n\nSocial fitness is real fitness: small reps, tracked honestly, repeated weekly. Left the apartment counts. One question counts. The streak builds the confidence — not vice versa.\n\nStart with one social rep → link in bio.",
    },
    ytTitle: "Your social life needs reps, not motivation",
    ytDescription: "Treat social rebuilding like training mileage. The feeling follows the rep." + YT_FOOT,
    hashtags: [...HT.core, ...HT.habit, "#discipline"],
    uploadNotes: "Fitness-audience crossover — works in gym/running hashtag neighborhoods too.",
  },
  {
    slug: "09-friendships-die-quietly",
    title: "Most adult friendships die quietly",
    thumbnailTitle: "Most adult friendships\ndie *quietly*",
    cta: "Link in bio.",
    register: "mirror",
    scenes: [
      { text: "Most adult friendships\ndon't end in a fight.", seconds: 4, big: true },
      { text: "They end in a\nrescheduled coffee.", seconds: 3.5, register: "mirror" },
      { text: "“We should catch up soon”\n→ six months of nothing.", seconds: 4, register: "mirror" },
      { text: "Nobody chose to end it.", sub: "Nobody chose to continue it either.", seconds: 4.5 },
      { text: "Friendship is a *default* problem.", sub: "Silence is the default. Contact is a choice.", seconds: 5 },
      { text: "One message today\nto someone drifting.", sub: "No apology for the gap. Just hello.", seconds: 4.5 },
      { text: "Link in bio.", seconds: 2.5 },
    ],
    voiceover: "Most adult friendships don't end in a fight. They end in a rescheduled coffee. 'We should catch up soon' — then six months of nothing. Nobody chose to end it. Nobody chose to continue it either. Friendship is a default problem: silence is the default, contact is a choice. One message today to someone drifting. No apology for the gap. Just hello.",
    captions: {
      generic: "Nobody chose to end it. Nobody chose to continue it either. Send the no-apology hello.",
      tiktok: "'we should catch up soon' is where friendships go to die #fyp",
      instagram: "The friendship didn't end. It just stopped being chosen.\n\nSilence is the default state of every adult relationship — contact is a decision someone has to make. Today: one message to someone drifting. Skip the apology for the gap; just say hello.\n\nLink in bio.",
    },
    ytTitle: "Most adult friendships die quietly — here's the pattern",
    ytDescription: "Not a fight. A rescheduled coffee. Why silence is the default and contact is a choice." + YT_FOOT,
    hashtags: [...HT.core, "#friendship"],
    uploadNotes: "Emotional peak of the catalog. Quiet piano audio. Expect shares to specific friends — that IS the distribution.",
  },
  {
    slug: "10-72-hour-rule",
    title: "The 72-hour follow-up rule",
    thumbnailTitle: "The *72-hour*\nfollow-up rule",
    cta: "Try the 7-day plan.",
    scenes: [
      { text: "The 72-hour rule:", seconds: 2.5, big: true },
      { text: "Follow up within 3 days\nof meeting someone.", sub: "Or accept you probably never will.", seconds: 4.5 },
      { text: "Day 1: they remember you clearly.", seconds: 3 },
      { text: "Day 3: still warm.\nNo reintroduction needed.", seconds: 3.5 },
      { text: "Week 2+: you're a stranger\nwith shared trivia.", seconds: 3.5, register: "mirror" },
      { text: "The message can be five words.", sub: "“Good meeting you at [place].”", seconds: 4 },
      { text: "Timing beats wording.\n*Every time.*", seconds: 3.5 },
      { text: "Try the *7-day plan*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "The seventy-two hour rule: follow up within three days of meeting someone, or accept you probably never will. Day one, they remember you clearly. Day three, still warm — no reintroduction needed. Week two, you're a stranger with shared trivia. The message can be five words: 'Good meeting you at run club.' Timing beats wording. Every time.",
    captions: {
      generic: "72 hours. After that you're a stranger with shared trivia. Timing beats wording.",
      tiktok: "day 3: still warm. week 2: stranger with shared trivia. #fyp",
      instagram: "Timing beats wording. Every time.\n\nThe 72-hour rule: follow up within three days or accept you probably never will. The message can be five words — the window is what matters.\n\nOrbit drafts it and tracks the window → link in bio.",
    },
    ytTitle: "The 72-hour follow-up rule (timing beats wording)",
    ytDescription: "Why three days is the window, and the five-word message that clears the bar." + YT_FOOT,
    hashtags: [...HT.core, "#socialskills", "#networking"],
    uploadNotes: "Rule-format content saves well. Number in the hook — keep '72-hour' in first frame.",
  },
  {
    slug: "11-after-35-operationally-annoying",
    title: "Making friends after 35 is operationally annoying",
    thumbnailTitle: "Making friends after 35 is\n*operationally annoying*",
    cta: "Try the 7-day plan.",
    scenes: [
      { text: "Making friends after 35\nisn't emotionally hard.", seconds: 4, big: true },
      { text: "It's *operationally annoying*.", seconds: 3, big: true },
      { text: "Everyone's calendar is full.\nEveryone's default is home.", seconds: 4 },
      { text: "Nothing repeats unless\nsomeone makes it repeat.", seconds: 3.5 },
      { text: "Which means friendship at this age\nis an *operations problem*.", sub: "Scheduling. Follow-up. Recurrence.", seconds: 5 },
      { text: "And operations problems\nhave systems.", sub: "Not vibes. Systems.", seconds: 4 },
      { text: "Try the *7-day plan*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "Making friends after thirty-five isn't emotionally hard. It's operationally annoying. Everyone's calendar is full. Everyone's default is home. Nothing repeats unless someone makes it repeat. Which means friendship at this age is an operations problem — scheduling, follow-up, recurrence. And operations problems have systems. Not vibes. Systems.",
    captions: {
      generic: "It's not emotionally hard. It's operationally annoying. And ops problems have systems.",
      tiktok: "friendship after 35 is an ops problem and nobody talks about it #fyp",
      instagram: "You're not bad at friendship. You're missing infrastructure.\n\nAfter 35, everyone's calendar is full and everyone's default is home — so friendship becomes an operations problem: scheduling, follow-up, recurrence. Ops problems don't need motivation. They need a system.\n\nTry the 7-day plan → link in bio.",
    },
    ytTitle: "Making friends after 35 is an operations problem",
    ytDescription: "Not emotionally hard — operationally annoying. And operations problems have systems." + YT_FOOT,
    hashtags: [...HT.core, "#over35", "#adulting"],
    uploadNotes: "Core demo callout — the 'operationally annoying' phrase is the shareable unit; keep it verbatim in caption.",
  },
  {
    slug: "12-remote-work-broke-rhythm",
    title: "Remote work quietly broke social rhythm",
    thumbnailTitle: "Remote work quietly broke\nyour *social rhythm*",
    cta: "Start with one social rep.",
    scenes: [
      { text: "Remote work didn't make you\nantisocial.", seconds: 3.5, big: true },
      { text: "It deleted the *infrastructure*.", seconds: 3 },
      { text: "The office was ambient contact:", sub: "hallway hellos, lunch invites,\nsomeone's birthday cake.", seconds: 5 },
      { text: "Zero effort. Daily reps.\nYou never noticed.", seconds: 3.5 },
      { text: "Now the reps are gone\nand nothing replaced them.", seconds: 4, register: "mirror" },
      { text: "You have to *design* what the office\ngave you for free.", sub: "Recurring events. Deliberate contact.", seconds: 5 },
      { text: "Start with *one social rep* today.", sub: "Link in bio.", seconds: 3.5 },
    ],
    voiceover: "Remote work didn't make you antisocial. It deleted the infrastructure. The office was ambient contact: hallway hellos, lunch invites, someone's birthday cake. Zero effort, daily reps — you never noticed. Now the reps are gone and nothing replaced them. You have to design what the office gave you for free. Recurring events. Deliberate contact.",
    captions: {
      generic: "The office was ambient social reps. Remote deleted them. Now you design the replacement.",
      tiktok: "remote work deleted your social infrastructure and called it flexibility #fyp",
      instagram: "You didn't become antisocial. Your infrastructure disappeared.\n\nThe office gave you daily ambient reps — hallway hellos, lunch invites — for free. Remote work deleted them without a replacement. The fix is designed, not wished for: recurring anchors, deliberate follow-up.\n\nStart with one rep → link in bio.",
    },
    ytTitle: "Remote work quietly broke your social life (here's the mechanism)",
    ytDescription: "The office was ambient social infrastructure. Remote deleted it. What to build instead." + YT_FOOT,
    hashtags: [...HT.core, ...HT.remote],
    uploadNotes: "Remote-work audiences are huge on all three platforms — tag accordingly, expect crossover.",
  },
  {
    slug: "13-new-city-nobody-integrates-you",
    title: "New city reset: nobody integrates you automatically",
    thumbnailTitle: "New city truth:\n*nobody integrates you*",
    cta: "Try the 7-day plan.",
    scenes: [
      { text: "Hard truth about\nmoving to a new city:", seconds: 3.5, big: true },
      { text: "Nobody is coming\nto integrate you.", seconds: 3.5, register: "mirror" },
      { text: "The city doesn't notice you arrived.", sub: "Eight months in, still nobody to call —\nthat's the default outcome, not a failure.", seconds: 5.5 },
      { text: "Integration is built, not granted:", seconds: 3 },
      { text: "Two recurring anchors.\nAttended weekly.", seconds: 3.5 },
      { text: "One follow-up per week\nto someone you met.", seconds: 3.5 },
      { text: "Ninety days of that\nand the city knows your face.", seconds: 4 },
      { text: "Try the *7-day plan*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "Hard truth about moving to a new city: nobody is coming to integrate you. The city doesn't notice you arrived. Eight months in, still nobody to call — that's the default outcome, not a personal failure. Integration is built, not granted: two recurring anchors, attended weekly. One follow-up per week to someone you met. Ninety days of that, and the city knows your face.",
    captions: {
      generic: "The city doesn't notice you arrived. Two anchors + one follow-up a week = integration.",
      tiktok: "8 months in a new city and nobody to call is the DEFAULT. here's the fix #fyp",
      instagram: "Nobody is coming to integrate you. That's not pessimism — it's the operating manual.\n\nNew-city integration is built: two recurring anchors attended weekly, one follow-up a week. Ninety days of that and the city knows your face.\n\nTry the 7-day plan → link in bio.",
    },
    ytTitle: "Moving cities as an adult: nobody integrates you automatically",
    ytDescription: "The default outcome is isolation — and the 90-day protocol that changes it." + YT_FOOT,
    hashtags: [...HT.core, ...HT.city],
    uploadNotes: "Evergreen — new-city search traffic is constant. Strong for YouTube Shorts especially.",
  },
  {
    slug: "14-post-divorce-rebuild",
    title: "Post-divorce social rebuild, without the drama",
    thumbnailTitle: "The post-divorce\nsocial *rebuild*",
    cta: "Join the Orbit beta.",
    scenes: [
      { text: "Nobody warns you:", sub: "divorce takes the couple-friends with it.", seconds: 4.5, big: true },
      { text: "Not from malice.\nFrom logistics.", sub: "The dinners were couple-shaped.", seconds: 4.5 },
      { text: "So you're rebuilding a social life\nfrom scratch at 40+.", seconds: 4 },
      { text: "Skip the reinvention montage.", sub: "You don't need a new personality.", seconds: 4 },
      { text: "You need a *rhythm*:", sub: "one recurring event, one follow-up,\none ordinary week at a time.", seconds: 5 },
      { text: "Quiet. Repeatable. Yours.", seconds: 3 },
      { text: "Join the *Orbit beta*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "Nobody warns you: divorce takes the couple-friends with it. Not from malice — from logistics. The dinners were couple-shaped. So you're rebuilding a social life from scratch at forty-plus. Skip the reinvention montage. You don't need a new personality. You need a rhythm: one recurring event, one follow-up, one ordinary week at a time. Quiet. Repeatable. Yours.",
    captions: {
      generic: "The dinners were couple-shaped. The rebuild is rhythm, not reinvention.",
      tiktok: "divorce takes the couple-friends. nobody says it out loud. #fyp",
      instagram: "You don't need a reinvention montage. You need a rhythm.\n\nDivorce quietly deletes the couple-shaped social life — not from malice, from logistics. The rebuild: one recurring event, one follow-up, one ordinary week at a time.\n\nJoin the beta → link in bio.",
    },
    ytTitle: "Rebuilding your social life after divorce (without the drama)",
    ytDescription: "The couple-friends leave with the marriage. The rebuild is rhythm, not reinvention." + YT_FOOT,
    hashtags: [...HT.core, ...HT.divorce],
    uploadNotes: "Handle with care in comments — empathetic, never glib. NEVER pivot to dating in replies.",
  },
  {
    slug: "15-introverts-repeatable-reps",
    title: "Introverts don't need more pressure. They need repeatable reps.",
    thumbnailTitle: "Introverts need\n*repeatable reps*,\nnot pressure",
    cta: "Try the Solo Night Generator.",
    scenes: [
      { text: "Worst advice introverts get:", sub: "“just put yourself out there.”", seconds: 4, big: true },
      { text: "Out *where*? For how long?\nDoing what?", seconds: 3.5 },
      { text: "Pressure isn't a plan.", seconds: 2.5 },
      { text: "What works is *structure*:", sub: "an event with a start and an end.\nOne micro-goal. An exit rule.", seconds: 5.5 },
      { text: "“Stay 45 minutes.\nAsk one person one question.\nThen you're free.”", seconds: 5 },
      { text: "Repeatable beats brave.", seconds: 3 },
      { text: "Try the *Solo Night Generator*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "The worst advice introverts get: 'just put yourself out there.' Out where? For how long? Doing what? Pressure isn't a plan. What works is structure: an event with a start and an end. One micro-goal. An exit rule. Stay forty-five minutes, ask one person one question, then you're free. Repeatable beats brave.",
    captions: {
      generic: "'Put yourself out there' isn't a plan. Structure + exit rule + one micro-goal is.",
      tiktok: "out WHERE? for how LONG? doing WHAT? pressure isn't a plan #introvert",
      instagram: "Repeatable beats brave.\n\nIntroverts don't need a push — they need structure: an event with a defined end, one micro-goal, and an exit rule that makes the door feel open. 'Stay 45 minutes, ask one question, then you're free' gets you out more than any pep talk.\n\nTry the Solo Night Generator → link in bio.",
    },
    ytTitle: "Introverts don't need pressure. They need repeatable reps.",
    ytDescription: "'Put yourself out there' isn't a plan. The exit-rule structure that actually works." + YT_FOOT,
    hashtags: [...HT.core, ...HT.intro],
    uploadNotes: "Introvert hashtag neighborhoods are the most engaged niche — expect strong saves and follows.",
  },
  {
    slug: "16-45-minutes-counts",
    title: "One 45-minute event counts",
    thumbnailTitle: "One 45-minute event\n*counts*",
    cta: "Save this for Friday night.",
    scenes: [
      { text: "Permission slip:", seconds: 2.5, big: true },
      { text: "45 minutes *counts*.", seconds: 3, big: true },
      { text: "You don't owe any event\nyour whole night.", seconds: 3.5 },
      { text: "Go. Stay 45 minutes.\nSay one hello. Leave.", seconds: 4 },
      { text: "That's a complete rep.", sub: "Not a partial one. Complete.", seconds: 4 },
      { text: "The dread shrinks when\nthe commitment does.", seconds: 4 },
      { text: "Save this for Friday night.", seconds: 3 },
    ],
    voiceover: "Permission slip: forty-five minutes counts. You don't owe any event your whole night. Go. Stay forty-five minutes. Say one hello. Leave. That's a complete rep — not a partial one. Complete. The dread shrinks when the commitment does.",
    captions: {
      generic: "45 minutes. One hello. Leave. That's a complete rep, not a partial one.",
      tiktok: "you don't owe the event your whole night. 45 min counts. #fyp",
      instagram: "The dread shrinks when the commitment does.\n\n45 minutes, one hello, leave — that's a complete social rep. Lowering the bar isn't cheating; it's the mechanism that gets you out the door at all.\n\nSave this for Friday night.",
    },
    ytTitle: "One 45-minute event counts (the permission slip)",
    ytDescription: "Shrink the commitment and the dread shrinks with it. 45 minutes is a complete rep." + YT_FOOT,
    hashtags: [...HT.core, ...HT.intro, "#anxietyfriendly"],
    uploadNotes: "Shortest, gentlest video. Great palate-cleanser between harder-truth posts.",
  },
  {
    slug: "17-repeat-exposure-wins",
    title: "Stop chasing novelty. Repeat exposure wins.",
    thumbnailTitle: "Stop chasing novelty.\n*Repeat exposure* wins.",
    cta: "Link in bio.",
    scenes: [
      { text: "You've tried 15 different events\nthis year.", seconds: 3.5, big: true },
      { text: "How many did you try *twice*?", seconds: 3, register: "mirror" },
      { text: "Novelty is a treadmill:", sub: "every night starts at stranger-zero.", seconds: 4.5 },
      { text: "Repetition compounds:", sub: "same room, same faces,\nfamiliarity doing the work.", seconds: 5 },
      { text: "The psychology is boring and real:", sub: "we like people we've *seen before*.", seconds: 4.5 },
      { text: "Pick one thing.\nGo three times.", seconds: 3.5 },
      { text: "Link in bio.", seconds: 2.5 },
    ],
    voiceover: "You've tried fifteen different events this year. How many did you try twice? Novelty is a treadmill — every night starts at stranger-zero. Repetition compounds: same room, same faces, familiarity doing the work. The psychology is boring and real: we like people we've seen before. Pick one thing. Go three times.",
    captions: {
      generic: "Novelty starts every night at stranger-zero. Repetition compounds. Pick one, go three times.",
      tiktok: "15 different events this year. tried none of them twice. that's the bug #fyp",
      instagram: "Every new event starts you at stranger-zero. The second and third visit is where the compounding happens.\n\nMere exposure is the most boring, most reliable force in social psychology: we warm to people we've simply seen before. Use it. One thing, three visits.\n\nLink in bio.",
    },
    ytTitle: "Stop chasing novelty — repeat exposure wins",
    ytDescription: "Fifteen events, none twice: the bug in most adult social lives. Why repetition compounds." + YT_FOOT,
    hashtags: [...HT.core, ...HT.habit],
    uploadNotes: "Sibling of 04/05 — space these across weeks, don't stack in one.",
  },
  {
    slug: "18-met-once-not-friends-yet",
    title: "The person you met once is not your friend yet",
    thumbnailTitle: "Met once ≠ *friends*",
    cta: "Start with one social rep.",
    register: "mirror",
    scenes: [
      { text: "Gentle reality check:", seconds: 2.5, big: true },
      { text: "The person you met once\nis not your friend *yet*.", seconds: 4 },
      { text: "One great conversation is\na doorway, not a relationship.", seconds: 4 },
      { text: "Don't over-invest:\nno essays, no intensity.", seconds: 3.5, register: "mirror" },
      { text: "Don't under-invest either:\nsilence closes the door.", seconds: 3.5, register: "mirror" },
      { text: "The move is *light + repeated*:", sub: "low-pressure message, shared setting,\nsee them again.", seconds: 5 },
      { text: "Keep it casual.\nLet the reps do the work.", seconds: 3.5 },
      { text: "Start with *one social rep*.", sub: "Link in bio.", seconds: 3 },
    ],
    voiceover: "Gentle reality check: the person you met once is not your friend yet. One great conversation is a doorway, not a relationship. Don't over-invest — no essays, no intensity. Don't under-invest either — silence closes the door. The move is light plus repeated: a low-pressure message, a shared setting, see them again. Keep it casual. Let the reps do the work.",
    captions: {
      generic: "One great conversation is a doorway, not a relationship. Light + repeated is the move.",
      tiktok: "one good conversation ≠ friendship. it's a doorway. walk through it lightly #fyp",
      instagram: "Not over-invested. Not ghosting. Light + repeated.\n\nOne great conversation is a doorway, not a relationship — treat it with proportion. A low-pressure follow-up, a shared recurring setting, and time do what intensity can't.\n\nStart with one social rep → link in bio.",
    },
    ytTitle: "The person you met once is not your friend yet",
    ytDescription: "The proportionality rule for new connections: light + repeated beats intense + rare." + YT_FOOT,
    hashtags: [...HT.core, "#socialskills"],
    uploadNotes: "The 'reality check' framing mirrors the in-app feature — mention that in a reply comment if asked.",
  },
  {
    slug: "19-orbit-in-30-seconds",
    title: "Orbit in 30 seconds",
    thumbnailTitle: "*Orbit* in 30 seconds",
    cta: "Join the Orbit beta.",
    scenes: [
      { text: "I built a private system for\nrebuilding a social life.", sub: "Here it is in 30 seconds.", seconds: 4.5, big: true },
      { text: "Tonight:", sub: "3 plans matched to your energy and budget.\nThe easy one still counts.", seconds: 5 },
      { text: "Events:", sub: "scored so recurring, conversation-friendly\nones rise to the top.", seconds: 5 },
      { text: "People:", sub: "a private tracker for who you met —\nwith follow-up drafts that sound like you.", seconds: 5.5 },
      { text: "It never posts, never matches,\nnever sends anything for you.", seconds: 4 },
      { text: "No feed. No performing.\nJust the loop.", seconds: 3.5 },
      { text: "Join the *Orbit beta*.", sub: "Free, no account. Link in bio.", seconds: 3.5 },
    ],
    voiceover: "I built a private system for rebuilding a social life. Here it is in thirty seconds. Tonight: three plans matched to your energy and budget — the easy one still counts. Events: scored so recurring, conversation-friendly ones rise to the top. People: a private tracker for who you met, with follow-up drafts that sound like you. It never posts, never matches, never sends anything for you. No feed. No performing. Just the loop.",
    captions: {
      generic: "A private system for rebuilding a social life. No feed, no matching, no performing. Free beta — link in bio.",
      tiktok: "i built a CRM for my social life because i kept losing weak ties. free beta in bio",
      instagram: "Orbit in 30 seconds:\n\n→ Tonight: 3 plans for your energy + budget\n→ Events: scored, recurring-weighted\n→ People: private tracker + follow-up drafts\n→ Never posts, never matches, never auto-sends\n\nNo feed. No performing. Just the loop. Free beta → link in bio.",
    },
    ytTitle: "I built a private app for rebuilding your social life — Orbit in 30 seconds",
    ytDescription: "The full product in 30 seconds: solo night plans, event scoring, a private people tracker, and follow-up drafts. Free beta." + YT_FOOT,
    hashtags: [...HT.core, "#buildinpublic", "#indieapp"],
    uploadNotes: "The product video. Post AFTER 5+ insight videos have run — audience first, pitch second. Consider a screen-recording remake in CapCut later using this script.",
  },
  {
    slug: "20-30-day-challenge",
    title: "The 30-day social rebuild challenge",
    thumbnailTitle: "The *30-day*\nsocial rebuild",
    cta: "Join the Orbit beta.",
    scenes: [
      { text: "The 30-day\nsocial rebuild challenge:", seconds: 3.5, big: true },
      { text: "Week 1: leave the apartment.", sub: "Solo-but-public counts. Motion over meaning.", seconds: 4.5 },
      { text: "Week 2: start conversations.", sub: "One question per outing. Learn one name.", seconds: 4.5 },
      { text: "Week 3: follow up.", sub: "Capture the weak tie. Send the message.", seconds: 4.5 },
      { text: "Week 4: build cadence.", sub: "Pick your anchors. Become a regular.", seconds: 4.5 },
      { text: "Miss a day? *Continue.*", sub: "Restarting is a trap.", seconds: 4, register: "mirror" },
      { text: "30 days. One ordinary rep at a time.", seconds: 3.5 },
      { text: "Join the *Orbit beta*.", sub: "The app runs the whole program. Link in bio.", seconds: 4 },
    ],
    voiceover: "The thirty-day social rebuild challenge. Week one: leave the apartment — solo-but-public counts, motion over meaning. Week two: start conversations — one question per outing, learn one name. Week three: follow up — capture the weak tie, send the message. Week four: build cadence — pick your anchors, become a regular. Miss a day? Continue. Restarting is a trap. Thirty days, one ordinary rep at a time.",
    captions: {
      generic: "Week 1 leave the apartment. Week 2 talk. Week 3 follow up. Week 4 build cadence. Miss a day → continue.",
      tiktok: "30 day social rebuild. week 1 is just leaving the apartment. who's in? #30daychallenge",
      instagram: "The 30-Day Social Rebuild:\n\nWeek 1 — Leave the apartment\nWeek 2 — Start conversations\nWeek 3 — Follow up\nWeek 4 — Build cadence\n\nMiss a day? Continue. Restarting is a trap.\n\nThe app runs the whole program → link in bio.",
    },
    ytTitle: "The 30-Day Social Rebuild Challenge (full protocol)",
    ytDescription: "Four weeks, one assignment a day, non-restart recovery. The complete program." + YT_FOOT,
    hashtags: [...HT.core, "#30daychallenge", ...HT.habit],
    uploadNotes: "Challenge format = comment magnet ('day 1' replies). Reply to every 'day 1' comment for a week — that's community seeding.",
  },
];
